import { ArrowUpRight, Mail, MapPin } from "lucide-react";
import { FormEvent, useState } from "react";
import { trpc } from "@/lib/trpc";
import { useQuoteCart } from "@/contexts/QuoteCartContext";

export default function Contact() {
  const [sent, setSent] = useState(false); const { items, clearCart } = useQuoteCart();
  const enquiry = trpc.enquiries.create.useMutation({ onSuccess: () => { clearCart(); setSent(true); } });
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); enquiry.mutate({ name: String(data.get("name") ?? ""), email: String(data.get("email") ?? ""), projectType: String(data.get("projectType") ?? "") as "Collection work" | "Bespoke sculpture" | "Spatial installation" | "Other enquiry", message: String(data.get("message") ?? ""), selectedWorks: items.map(item => `${item.title} × ${item.quantity}`) }); }
  return <main className="page contact-page"><section className="contact-intro"><p className="eyebrow">Contact</p><h1>Tell us about<br />the <em>space.</em></h1><p>Use this enquiry form to begin a conversation about a sculpture, a bespoke form or a site-specific idea.</p></section><section className="contact-layout"><form className="contact-form" onSubmit={onSubmit}>{sent ? <div className="form-success"><p className="eyebrow">Request received</p><h2>Thank you.</h2><p>Your request has been sent to the studio. A member of the team will review the brief and return via the email address you provided.</p></div> : <><label>Full name<input required name="name" autoComplete="name" minLength={2} maxLength={160} /></label><label>Email<input required type="email" name="email" autoComplete="email" maxLength={320} /></label><label>Project type<select name="projectType" required defaultValue=""><option value="" disabled>Select an option</option><option>Collection work</option><option>Bespoke sculpture</option><option>Spatial installation</option><option>Other enquiry</option></select></label><label>Project outline<textarea required name="message" rows={5} minLength={10} maxLength={5000} placeholder="Tell us about the space, desired scale and timeline." /></label>{items.length > 0 && <div className="selected-works"><p className="eyebrow">Selected works</p>{items.map(item => <span key={item.id}>{item.title} × {item.quantity}</span>)}</div>}{enquiry.error && <p className="form-error" role="alert">We could not submit the request. Please try again or email the studio directly.</p>}<button className="button button--dark" type="submit" disabled={enquiry.isPending}>{enquiry.isPending ? "Sending…" : <>Send enquiry <ArrowUpRight size={17} /></>}</button></>}</form><aside className="contact-details"><p className="eyebrow">Studio details</p><a href="mailto:ikimedyapromosyon@gmail.com"><Mail size={18} />ikimedyapromosyon@gmail.com</a><a href="https://g.co/kgs/vbaS4cj" target="_blank" rel="noreferrer"><MapPin size={18} />Reşatbey Mh., 62017. Sk. 36/B<br />Seyhan / Adana</a><p>The company profile and contact details shown here are retained from ikimedyatanitim.com.</p></aside></section></main>;
}
