export type SculptureSize = "Büyük" | "Çok büyük";
export type SculptureStyle = "Mimari" | "Organik" | "Geometrik";
export type Sculpture = { id: string; slug: string; index: string; title: string; category: string; description: string; dimensions: string; material: string; finish: string; production: string; size: SculptureSize; style: SculptureStyle; priceCents: number | null; arReady: boolean; arModelUrl?: string; arIosModelUrl?: string; visual: "arch" | "column" | "loop"; };

/** Sunum kayıtlarıdır. Stüdyo onaylayana kadar fiyatlar teklif üzerine kalır. */
export const sculptures: Sculpture[] = [
  { id: "form-01", slug: "form-01", index: "01", title: "FORM / 01", category: "Mekânsal obje", description: "Geniş iç mekânlar ve kamusal alanlar için geliştirilen yapılandırılabilir mimari bir form.", dimensions: "Her kurulum için belirlenir", material: "Büyük ölçekli 3D baskı kompoziti; projeye göre belirlenir", finish: "Projeye göre seçilen mat monokrom yüzey", production: "Mekânsal ve teknik değerlendirme sonrasında, briefe göre üretilir", size: "Büyük", style: "Mimari", priceCents: null, arReady: false, visual: "arch" },
  { id: "volume-02", slug: "volume-02", index: "02", title: "VOLUME / 02", category: "İç mekân heykeli", description: "Özel mekânlar için hacim, oran ve sakin yüzey ritmi üzerine dikey bir çalışma.", dimensions: "Her kurulum için belirlenir", material: "Büyük ölçekli 3D baskı kompoziti; projeye göre belirlenir", finish: "Projeye göre seçilen mat monokrom yüzey", production: "Mekânsal ve teknik değerlendirme sonrasında, briefe göre üretilir", size: "Çok büyük", style: "Organik", priceCents: null, arReady: false, visual: "column" },
  { id: "void-03", slug: "void-03", index: "03", title: "VOID / 03", category: "Odak parçası", description: "Lobiler, perakende alanları ve sergi mekânları için odak noktası olarak tasarlanmış süreklilik arz eden form.", dimensions: "Her kurulum için belirlenir", material: "Büyük ölçekli 3D baskı kompoziti; projeye göre belirlenir", finish: "Projeye göre seçilen mat monokrom yüzey", production: "Mekânsal ve teknik değerlendirme sonrasında, briefe göre üretilir", size: "Büyük", style: "Geometrik", priceCents: null, arReady: false, visual: "loop" },
];
export function getSculpture(slug: string) { return sculptures.find(sculpture => sculpture.slug === slug); }
