import "@google/model-viewer";
import { createElement, useEffect, useRef, useState } from "react";
import { AlertCircle, Box, LoaderCircle, ScanLine } from "lucide-react";
import type { Sculpture } from "@shared/catalog";
import { getARPreviewAvailability } from "@shared/arPreview";

export default function ARViewer({ sculpture }: { sculpture: Sculpture }) {
  const availability = getARPreviewAvailability(sculpture); const modelRef = useRef<HTMLElement | null>(null); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { setStatus("loading"); const model = modelRef.current; if (!model || !availability.available) return; const onLoad = () => setStatus("ready"); const onError = () => setStatus("error"); model.addEventListener("load", onLoad); model.addEventListener("error", onError); return () => { model.removeEventListener("load", onLoad); model.removeEventListener("error", onError); }; }, [availability.available, sculpture.arModelUrl]);
  if (!availability.available) return <section className="ar-panel"><div className="ar-panel__icon"><ScanLine size={27} /></div><div><p className="eyebrow">AR önizleme</p><h3>3D model talep üzerine</h3><p>Seçili projeler için stüdyo onaylı GLB/GLTF ve iOS için USDZ modeli sağlanabilir. Uyumlu cihazlarda mekân içi önizleme bu alanda açılır.</p></div></section>;
  return <section className="grid gap-8 border-y border-[#cbcbc4] px-[4vw] py-9 md:grid-cols-[.7fr_1.3fr] md:items-center"><div><p className="eyebrow">AR önizleme</p><h3 className="mb-2 mt-1 text-xl font-bold tracking-[-.04em]">Mekânınızda görün</h3><p className="max-w-sm text-sm leading-6 text-[#666661]">Uyumlu cihazınızda AR düğmesini açarak stüdyo onaylı işi gerçek ölçekte bulunduğu ortama yerleştirin.</p><p className="mt-3 text-xs leading-5 text-[#666661]">{availability.supportsQuickLook ? "iOS için Quick Look modeli hazır." : "iOS için Quick Look önizlemesi USDZ dosyası eklendiğinde etkinleşir."}</p>{status === "loading" && <p className="mt-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.1em] text-[#6a6a66]"><LoaderCircle size={14} className="animate-spin" /> Model yükleniyor</p>}{status === "ready" && <p className="mt-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.1em] text-[#6a6a66]"><Box size={14} /> AR için hazır</p>}{status === "error" && <p className="mt-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.1em] text-[#8d1c1c]"><AlertCircle size={14} /> Model yüklenemedi</p>}</div>{createElement("model-viewer", { ref: (node: HTMLElement | null) => { modelRef.current = node; }, src: sculpture.arModelUrl, "ios-src": sculpture.arIosModelUrl, alt: `${sculpture.title} 3D modeli`, ar: true, "ar-modes": "webxr scene-viewer quick-look", "camera-controls": true, "shadow-intensity": "0.8", "environment-image": "neutral", style: { width: "100%", height: "430px", background: "#e0e0da" } })}</section>;
}
